# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'share1car' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Firebase
  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
  # Mapping
  pod 'Mapbox-iOS-SDK', '~> 5.4'
  pod 'MapboxGeocoder.swift', '~> 0.11'
  pod 'MapboxDirections.swift', '~> 0.30'
  pod 'MapboxNavigation'
  pod 'Polyline', '~> 4.0'
  pod 'Turf', '~> 0.3'

  # UI
  pod 'BulletinBoard'
  pod 'Loaf'
  pod "RGSnackBar"
  pod 'MaterialComponents/Snackbar'
  pod 'JGProgressHUD'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'SDWebImage', '~> 5.0'
  pod 'BadgeSwift'
  pod 'Cosmos', '~> 20.0'
  pod 'AwesomeSpotlightView'
  # Layout
  pod "EasyPeasy"
  
  # User Input
  pod 'Eureka'
  
  
  # Developer tools
#  pod 'Reveal-SDK', :configurations => ['Debug']
  
  # Pods for share1car

end
