# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'share1car' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  pod 'Firebase/Database'

  # Pods for share1car

end
